//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.17 at 02:04:24 PM YEKT 
//


package com.soapdataservice.app.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="lowValue" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="highValue" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lowValue",
    "highValue"
})
@XmlRootElement(name = "getItemsByPriceRangeRequest")
public class GetItemsByPriceRangeRequest {

    protected int lowValue;
    protected int highValue;

    /**
     * Gets the value of the lowValue property.
     * 
     */
    public int getLowValue() {
        return lowValue;
    }

    /**
     * Sets the value of the lowValue property.
     * 
     */
    public void setLowValue(int value) {
        this.lowValue = value;
    }

    /**
     * Gets the value of the highValue property.
     * 
     */
    public int getHighValue() {
        return highValue;
    }

    /**
     * Sets the value of the highValue property.
     * 
     */
    public void setHighValue(int value) {
        this.highValue = value;
    }

}
