//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.17 at 02:04:24 PM YEKT 
//


package com.soapdataservice.app.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="updatedBrand" type="{http://com/soapdataservice/app/dto}brandDto"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "updatedBrand"
})
@XmlRootElement(name = "updateBrandResponse")
public class UpdateBrandResponse {

    @XmlElement(required = true)
    protected BrandDto updatedBrand;

    /**
     * Gets the value of the updatedBrand property.
     * 
     * @return
     *     possible object is
     *     {@link BrandDto }
     *     
     */
    public BrandDto getUpdatedBrand() {
        return updatedBrand;
    }

    /**
     * Sets the value of the updatedBrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrandDto }
     *     
     */
    public void setUpdatedBrand(BrandDto value) {
        this.updatedBrand = value;
    }

}
