//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.13 at 06:05:43 PM YEKT 
//


package database.dto.app.producingservice.com;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for createDataDto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="createDataDto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="itemsMeta" type="{http://com.producingservice.app.dto.database}metaContainerDto" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="brandsMeta" type="{http://com.producingservice.app.dto.database}metaContainerDto" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="manufacturersMeta" type="{http://com.producingservice.app.dto.database}metaContainerDto" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="categoriesMeta" type="{http://com.producingservice.app.dto.database}metaContainerDto" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createDataDto", propOrder = {
    "itemsMeta",
    "brandsMeta",
    "manufacturersMeta",
    "categoriesMeta"
})
public class CreateDataDto {

    @XmlElement(nillable = true)
    protected List<MetaContainerDto> itemsMeta;
    @XmlElement(nillable = true)
    protected List<MetaContainerDto> brandsMeta;
    @XmlElement(nillable = true)
    protected List<MetaContainerDto> manufacturersMeta;
    @XmlElement(nillable = true)
    protected List<MetaContainerDto> categoriesMeta;

    /**
     * Gets the value of the itemsMeta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemsMeta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemsMeta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetaContainerDto }
     * 
     * 
     */
    public List<MetaContainerDto> getItemsMeta() {
        if (itemsMeta == null) {
            itemsMeta = new ArrayList<MetaContainerDto>();
        }
        return this.itemsMeta;
    }

    /**
     * Gets the value of the brandsMeta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the brandsMeta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBrandsMeta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetaContainerDto }
     * 
     * 
     */
    public List<MetaContainerDto> getBrandsMeta() {
        if (brandsMeta == null) {
            brandsMeta = new ArrayList<MetaContainerDto>();
        }
        return this.brandsMeta;
    }

    /**
     * Gets the value of the manufacturersMeta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the manufacturersMeta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManufacturersMeta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetaContainerDto }
     * 
     * 
     */
    public List<MetaContainerDto> getManufacturersMeta() {
        if (manufacturersMeta == null) {
            manufacturersMeta = new ArrayList<MetaContainerDto>();
        }
        return this.manufacturersMeta;
    }

    /**
     * Gets the value of the categoriesMeta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categoriesMeta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategoriesMeta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetaContainerDto }
     * 
     * 
     */
    public List<MetaContainerDto> getCategoriesMeta() {
        if (categoriesMeta == null) {
            categoriesMeta = new ArrayList<MetaContainerDto>();
        }
        return this.categoriesMeta;
    }

}
