//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.13 at 06:05:43 PM YEKT 
//


package database.dto.app.producingservice.com;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the database.dto.app.producingservice.com package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: database.dto.app.producingservice.com
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetItemByIdRequest }
     * 
     */
    public GetItemByIdRequest createGetItemByIdRequest() {
        return new GetItemByIdRequest();
    }

    /**
     * Create an instance of {@link GetItemByIdResponse }
     * 
     */
    public GetItemByIdResponse createGetItemByIdResponse() {
        return new GetItemByIdResponse();
    }

    /**
     * Create an instance of {@link ItemDto }
     * 
     */
    public ItemDto createItemDto() {
        return new ItemDto();
    }

    /**
     * Create an instance of {@link GetItemByNameRequest }
     * 
     */
    public GetItemByNameRequest createGetItemByNameRequest() {
        return new GetItemByNameRequest();
    }

    /**
     * Create an instance of {@link GetItemByNameResponse }
     * 
     */
    public GetItemByNameResponse createGetItemByNameResponse() {
        return new GetItemByNameResponse();
    }

    /**
     * Create an instance of {@link CreateItemRequest }
     * 
     */
    public CreateItemRequest createCreateItemRequest() {
        return new CreateItemRequest();
    }

    /**
     * Create an instance of {@link CreateItemResponse }
     * 
     */
    public CreateItemResponse createCreateItemResponse() {
        return new CreateItemResponse();
    }

    /**
     * Create an instance of {@link UpdateItemRequest }
     * 
     */
    public UpdateItemRequest createUpdateItemRequest() {
        return new UpdateItemRequest();
    }

    /**
     * Create an instance of {@link UpdateItemResponse }
     * 
     */
    public UpdateItemResponse createUpdateItemResponse() {
        return new UpdateItemResponse();
    }

    /**
     * Create an instance of {@link DeleteItemByIdRequest }
     * 
     */
    public DeleteItemByIdRequest createDeleteItemByIdRequest() {
        return new DeleteItemByIdRequest();
    }

    /**
     * Create an instance of {@link DeleteItemByIdResponse }
     * 
     */
    public DeleteItemByIdResponse createDeleteItemByIdResponse() {
        return new DeleteItemByIdResponse();
    }

    /**
     * Create an instance of {@link GetAllItemsRequest }
     * 
     */
    public GetAllItemsRequest createGetAllItemsRequest() {
        return new GetAllItemsRequest();
    }

    /**
     * Create an instance of {@link GetAllItemsResponse }
     * 
     */
    public GetAllItemsResponse createGetAllItemsResponse() {
        return new GetAllItemsResponse();
    }

    /**
     * Create an instance of {@link GetItemsByBrandIdRequest }
     * 
     */
    public GetItemsByBrandIdRequest createGetItemsByBrandIdRequest() {
        return new GetItemsByBrandIdRequest();
    }

    /**
     * Create an instance of {@link GetItemsByBrandIdResponse }
     * 
     */
    public GetItemsByBrandIdResponse createGetItemsByBrandIdResponse() {
        return new GetItemsByBrandIdResponse();
    }

    /**
     * Create an instance of {@link GetItemsByManufacturerIdRequest }
     * 
     */
    public GetItemsByManufacturerIdRequest createGetItemsByManufacturerIdRequest() {
        return new GetItemsByManufacturerIdRequest();
    }

    /**
     * Create an instance of {@link GetItemsByManufacturerIdResponse }
     * 
     */
    public GetItemsByManufacturerIdResponse createGetItemsByManufacturerIdResponse() {
        return new GetItemsByManufacturerIdResponse();
    }

    /**
     * Create an instance of {@link GetItemsByCategoryIdRequest }
     * 
     */
    public GetItemsByCategoryIdRequest createGetItemsByCategoryIdRequest() {
        return new GetItemsByCategoryIdRequest();
    }

    /**
     * Create an instance of {@link GetItemsByCategoryIdResponse }
     * 
     */
    public GetItemsByCategoryIdResponse createGetItemsByCategoryIdResponse() {
        return new GetItemsByCategoryIdResponse();
    }

    /**
     * Create an instance of {@link GetItemsByCategoryNameRequest }
     * 
     */
    public GetItemsByCategoryNameRequest createGetItemsByCategoryNameRequest() {
        return new GetItemsByCategoryNameRequest();
    }

    /**
     * Create an instance of {@link GetItemsByCategoryNameResponse }
     * 
     */
    public GetItemsByCategoryNameResponse createGetItemsByCategoryNameResponse() {
        return new GetItemsByCategoryNameResponse();
    }

    /**
     * Create an instance of {@link GetItemsByBrandNameRequest }
     * 
     */
    public GetItemsByBrandNameRequest createGetItemsByBrandNameRequest() {
        return new GetItemsByBrandNameRequest();
    }

    /**
     * Create an instance of {@link GetItemsByBrandNameResponse }
     * 
     */
    public GetItemsByBrandNameResponse createGetItemsByBrandNameResponse() {
        return new GetItemsByBrandNameResponse();
    }

    /**
     * Create an instance of {@link GetItemsByManufacturerNameRequest }
     * 
     */
    public GetItemsByManufacturerNameRequest createGetItemsByManufacturerNameRequest() {
        return new GetItemsByManufacturerNameRequest();
    }

    /**
     * Create an instance of {@link GetItemsByManufacturerNameResponse }
     * 
     */
    public GetItemsByManufacturerNameResponse createGetItemsByManufacturerNameResponse() {
        return new GetItemsByManufacturerNameResponse();
    }

    /**
     * Create an instance of {@link GetItemsByDescriptionRequest }
     * 
     */
    public GetItemsByDescriptionRequest createGetItemsByDescriptionRequest() {
        return new GetItemsByDescriptionRequest();
    }

    /**
     * Create an instance of {@link GetItemsByDescriptionResponse }
     * 
     */
    public GetItemsByDescriptionResponse createGetItemsByDescriptionResponse() {
        return new GetItemsByDescriptionResponse();
    }

    /**
     * Create an instance of {@link GetItemsByPriceRangeRequest }
     * 
     */
    public GetItemsByPriceRangeRequest createGetItemsByPriceRangeRequest() {
        return new GetItemsByPriceRangeRequest();
    }

    /**
     * Create an instance of {@link GetItemsByPriceRangeResponse }
     * 
     */
    public GetItemsByPriceRangeResponse createGetItemsByPriceRangeResponse() {
        return new GetItemsByPriceRangeResponse();
    }

    /**
     * Create an instance of {@link GetBrandByIdRequest }
     * 
     */
    public GetBrandByIdRequest createGetBrandByIdRequest() {
        return new GetBrandByIdRequest();
    }

    /**
     * Create an instance of {@link GetBrandByIdResponse }
     * 
     */
    public GetBrandByIdResponse createGetBrandByIdResponse() {
        return new GetBrandByIdResponse();
    }

    /**
     * Create an instance of {@link BrandDto }
     * 
     */
    public BrandDto createBrandDto() {
        return new BrandDto();
    }

    /**
     * Create an instance of {@link GetBrandByNameRequest }
     * 
     */
    public GetBrandByNameRequest createGetBrandByNameRequest() {
        return new GetBrandByNameRequest();
    }

    /**
     * Create an instance of {@link GetBrandByNameResponse }
     * 
     */
    public GetBrandByNameResponse createGetBrandByNameResponse() {
        return new GetBrandByNameResponse();
    }

    /**
     * Create an instance of {@link GetBrandByItemIdRequest }
     * 
     */
    public GetBrandByItemIdRequest createGetBrandByItemIdRequest() {
        return new GetBrandByItemIdRequest();
    }

    /**
     * Create an instance of {@link GetBrandByItemIdResponse }
     * 
     */
    public GetBrandByItemIdResponse createGetBrandByItemIdResponse() {
        return new GetBrandByItemIdResponse();
    }

    /**
     * Create an instance of {@link GetBrandByItemNameRequest }
     * 
     */
    public GetBrandByItemNameRequest createGetBrandByItemNameRequest() {
        return new GetBrandByItemNameRequest();
    }

    /**
     * Create an instance of {@link GetBrandByItemNameResponse }
     * 
     */
    public GetBrandByItemNameResponse createGetBrandByItemNameResponse() {
        return new GetBrandByItemNameResponse();
    }

    /**
     * Create an instance of {@link CreateBrandRequest }
     * 
     */
    public CreateBrandRequest createCreateBrandRequest() {
        return new CreateBrandRequest();
    }

    /**
     * Create an instance of {@link CreateBrandResponse }
     * 
     */
    public CreateBrandResponse createCreateBrandResponse() {
        return new CreateBrandResponse();
    }

    /**
     * Create an instance of {@link UpdateBrandRequest }
     * 
     */
    public UpdateBrandRequest createUpdateBrandRequest() {
        return new UpdateBrandRequest();
    }

    /**
     * Create an instance of {@link UpdateBrandResponse }
     * 
     */
    public UpdateBrandResponse createUpdateBrandResponse() {
        return new UpdateBrandResponse();
    }

    /**
     * Create an instance of {@link DeleteBrandByIdRequest }
     * 
     */
    public DeleteBrandByIdRequest createDeleteBrandByIdRequest() {
        return new DeleteBrandByIdRequest();
    }

    /**
     * Create an instance of {@link DeleteBrandByIdResponse }
     * 
     */
    public DeleteBrandByIdResponse createDeleteBrandByIdResponse() {
        return new DeleteBrandByIdResponse();
    }

    /**
     * Create an instance of {@link GetAllBrandsRequest }
     * 
     */
    public GetAllBrandsRequest createGetAllBrandsRequest() {
        return new GetAllBrandsRequest();
    }

    /**
     * Create an instance of {@link GetAllBrandsResponse }
     * 
     */
    public GetAllBrandsResponse createGetAllBrandsResponse() {
        return new GetAllBrandsResponse();
    }

    /**
     * Create an instance of {@link GetAllBrandsByManufacturerIdRequest }
     * 
     */
    public GetAllBrandsByManufacturerIdRequest createGetAllBrandsByManufacturerIdRequest() {
        return new GetAllBrandsByManufacturerIdRequest();
    }

    /**
     * Create an instance of {@link GetAllBrandsByManufacturerIdResponse }
     * 
     */
    public GetAllBrandsByManufacturerIdResponse createGetAllBrandsByManufacturerIdResponse() {
        return new GetAllBrandsByManufacturerIdResponse();
    }

    /**
     * Create an instance of {@link GetAllBrandsByManufacturerNameRequest }
     * 
     */
    public GetAllBrandsByManufacturerNameRequest createGetAllBrandsByManufacturerNameRequest() {
        return new GetAllBrandsByManufacturerNameRequest();
    }

    /**
     * Create an instance of {@link GetAllBrandsByManufacturerNameResponse }
     * 
     */
    public GetAllBrandsByManufacturerNameResponse createGetAllBrandsByManufacturerNameResponse() {
        return new GetAllBrandsByManufacturerNameResponse();
    }

    /**
     * Create an instance of {@link GetAllBrandsByCountryRequest }
     * 
     */
    public GetAllBrandsByCountryRequest createGetAllBrandsByCountryRequest() {
        return new GetAllBrandsByCountryRequest();
    }

    /**
     * Create an instance of {@link GetAllBrandsByCountryResponse }
     * 
     */
    public GetAllBrandsByCountryResponse createGetAllBrandsByCountryResponse() {
        return new GetAllBrandsByCountryResponse();
    }

    /**
     * Create an instance of {@link GetAllBrandsByCityRequest }
     * 
     */
    public GetAllBrandsByCityRequest createGetAllBrandsByCityRequest() {
        return new GetAllBrandsByCityRequest();
    }

    /**
     * Create an instance of {@link GetAllBrandsByCityResponse }
     * 
     */
    public GetAllBrandsByCityResponse createGetAllBrandsByCityResponse() {
        return new GetAllBrandsByCityResponse();
    }

    /**
     * Create an instance of {@link GetManufacturerByIdRequest }
     * 
     */
    public GetManufacturerByIdRequest createGetManufacturerByIdRequest() {
        return new GetManufacturerByIdRequest();
    }

    /**
     * Create an instance of {@link GetManufacturerByIdResponse }
     * 
     */
    public GetManufacturerByIdResponse createGetManufacturerByIdResponse() {
        return new GetManufacturerByIdResponse();
    }

    /**
     * Create an instance of {@link ManufacturerDto }
     * 
     */
    public ManufacturerDto createManufacturerDto() {
        return new ManufacturerDto();
    }

    /**
     * Create an instance of {@link GetManufacturerByNameRequest }
     * 
     */
    public GetManufacturerByNameRequest createGetManufacturerByNameRequest() {
        return new GetManufacturerByNameRequest();
    }

    /**
     * Create an instance of {@link GetManufacturerByNameResponse }
     * 
     */
    public GetManufacturerByNameResponse createGetManufacturerByNameResponse() {
        return new GetManufacturerByNameResponse();
    }

    /**
     * Create an instance of {@link GetManufacturerByItemIdRequest }
     * 
     */
    public GetManufacturerByItemIdRequest createGetManufacturerByItemIdRequest() {
        return new GetManufacturerByItemIdRequest();
    }

    /**
     * Create an instance of {@link GetManufacturerByItemIdResponse }
     * 
     */
    public GetManufacturerByItemIdResponse createGetManufacturerByItemIdResponse() {
        return new GetManufacturerByItemIdResponse();
    }

    /**
     * Create an instance of {@link GetManufacturerByItemNameRequest }
     * 
     */
    public GetManufacturerByItemNameRequest createGetManufacturerByItemNameRequest() {
        return new GetManufacturerByItemNameRequest();
    }

    /**
     * Create an instance of {@link GetManufacturerByItemNameResponse }
     * 
     */
    public GetManufacturerByItemNameResponse createGetManufacturerByItemNameResponse() {
        return new GetManufacturerByItemNameResponse();
    }

    /**
     * Create an instance of {@link CreateManufacturerRequest }
     * 
     */
    public CreateManufacturerRequest createCreateManufacturerRequest() {
        return new CreateManufacturerRequest();
    }

    /**
     * Create an instance of {@link CreateManufacturerResponse }
     * 
     */
    public CreateManufacturerResponse createCreateManufacturerResponse() {
        return new CreateManufacturerResponse();
    }

    /**
     * Create an instance of {@link UpdateManufacturerRequest }
     * 
     */
    public UpdateManufacturerRequest createUpdateManufacturerRequest() {
        return new UpdateManufacturerRequest();
    }

    /**
     * Create an instance of {@link UpdateManufacturerResponse }
     * 
     */
    public UpdateManufacturerResponse createUpdateManufacturerResponse() {
        return new UpdateManufacturerResponse();
    }

    /**
     * Create an instance of {@link DeleteManufacturerByIdRequest }
     * 
     */
    public DeleteManufacturerByIdRequest createDeleteManufacturerByIdRequest() {
        return new DeleteManufacturerByIdRequest();
    }

    /**
     * Create an instance of {@link DeleteManufacturerByIdResponse }
     * 
     */
    public DeleteManufacturerByIdResponse createDeleteManufacturerByIdResponse() {
        return new DeleteManufacturerByIdResponse();
    }

    /**
     * Create an instance of {@link GetAllManufacturersRequest }
     * 
     */
    public GetAllManufacturersRequest createGetAllManufacturersRequest() {
        return new GetAllManufacturersRequest();
    }

    /**
     * Create an instance of {@link GetAllManufacturersResponse }
     * 
     */
    public GetAllManufacturersResponse createGetAllManufacturersResponse() {
        return new GetAllManufacturersResponse();
    }

    /**
     * Create an instance of {@link GetAllManufacturersByBrandNameRequest }
     * 
     */
    public GetAllManufacturersByBrandNameRequest createGetAllManufacturersByBrandNameRequest() {
        return new GetAllManufacturersByBrandNameRequest();
    }

    /**
     * Create an instance of {@link GetAllManufacturersByBrandNameResponse }
     * 
     */
    public GetAllManufacturersByBrandNameResponse createGetAllManufacturersByBrandNameResponse() {
        return new GetAllManufacturersByBrandNameResponse();
    }

    /**
     * Create an instance of {@link GetAllManufacturersByBrandIdRequest }
     * 
     */
    public GetAllManufacturersByBrandIdRequest createGetAllManufacturersByBrandIdRequest() {
        return new GetAllManufacturersByBrandIdRequest();
    }

    /**
     * Create an instance of {@link GetAllManufacturersByBrandIdResponse }
     * 
     */
    public GetAllManufacturersByBrandIdResponse createGetAllManufacturersByBrandIdResponse() {
        return new GetAllManufacturersByBrandIdResponse();
    }

    /**
     * Create an instance of {@link GetAllManufacturersByCountryRequest }
     * 
     */
    public GetAllManufacturersByCountryRequest createGetAllManufacturersByCountryRequest() {
        return new GetAllManufacturersByCountryRequest();
    }

    /**
     * Create an instance of {@link GetAllManufacturersByCountryResponse }
     * 
     */
    public GetAllManufacturersByCountryResponse createGetAllManufacturersByCountryResponse() {
        return new GetAllManufacturersByCountryResponse();
    }

    /**
     * Create an instance of {@link GetAllManufacturersByCityRequest }
     * 
     */
    public GetAllManufacturersByCityRequest createGetAllManufacturersByCityRequest() {
        return new GetAllManufacturersByCityRequest();
    }

    /**
     * Create an instance of {@link GetAllManufacturersByCityResponse }
     * 
     */
    public GetAllManufacturersByCityResponse createGetAllManufacturersByCityResponse() {
        return new GetAllManufacturersByCityResponse();
    }

    /**
     * Create an instance of {@link GetCategoryByIdRequest }
     * 
     */
    public GetCategoryByIdRequest createGetCategoryByIdRequest() {
        return new GetCategoryByIdRequest();
    }

    /**
     * Create an instance of {@link GetCategoryByIdResponse }
     * 
     */
    public GetCategoryByIdResponse createGetCategoryByIdResponse() {
        return new GetCategoryByIdResponse();
    }

    /**
     * Create an instance of {@link CategoryDto }
     * 
     */
    public CategoryDto createCategoryDto() {
        return new CategoryDto();
    }

    /**
     * Create an instance of {@link GetCategoryByNameRequest }
     * 
     */
    public GetCategoryByNameRequest createGetCategoryByNameRequest() {
        return new GetCategoryByNameRequest();
    }

    /**
     * Create an instance of {@link GetCategoryByNameResponse }
     * 
     */
    public GetCategoryByNameResponse createGetCategoryByNameResponse() {
        return new GetCategoryByNameResponse();
    }

    /**
     * Create an instance of {@link CreateCategoryRequest }
     * 
     */
    public CreateCategoryRequest createCreateCategoryRequest() {
        return new CreateCategoryRequest();
    }

    /**
     * Create an instance of {@link CreateCategoryResponse }
     * 
     */
    public CreateCategoryResponse createCreateCategoryResponse() {
        return new CreateCategoryResponse();
    }

    /**
     * Create an instance of {@link UpdateCategoryRequest }
     * 
     */
    public UpdateCategoryRequest createUpdateCategoryRequest() {
        return new UpdateCategoryRequest();
    }

    /**
     * Create an instance of {@link UpdateCategoryResponse }
     * 
     */
    public UpdateCategoryResponse createUpdateCategoryResponse() {
        return new UpdateCategoryResponse();
    }

    /**
     * Create an instance of {@link DeleteCategoryByIdRequest }
     * 
     */
    public DeleteCategoryByIdRequest createDeleteCategoryByIdRequest() {
        return new DeleteCategoryByIdRequest();
    }

    /**
     * Create an instance of {@link DeleteCategoryByIdResponse }
     * 
     */
    public DeleteCategoryByIdResponse createDeleteCategoryByIdResponse() {
        return new DeleteCategoryByIdResponse();
    }

    /**
     * Create an instance of {@link GetAllCategoriesRequest }
     * 
     */
    public GetAllCategoriesRequest createGetAllCategoriesRequest() {
        return new GetAllCategoriesRequest();
    }

    /**
     * Create an instance of {@link GetAllCategoriesResponse }
     * 
     */
    public GetAllCategoriesResponse createGetAllCategoriesResponse() {
        return new GetAllCategoriesResponse();
    }

    /**
     * Create an instance of {@link GetAllCategoriesByItemNameRequest }
     * 
     */
    public GetAllCategoriesByItemNameRequest createGetAllCategoriesByItemNameRequest() {
        return new GetAllCategoriesByItemNameRequest();
    }

    /**
     * Create an instance of {@link GetAllCategoriesByItemNameResponse }
     * 
     */
    public GetAllCategoriesByItemNameResponse createGetAllCategoriesByItemNameResponse() {
        return new GetAllCategoriesByItemNameResponse();
    }

    /**
     * Create an instance of {@link GetAllCategoriesByItemIdRequest }
     * 
     */
    public GetAllCategoriesByItemIdRequest createGetAllCategoriesByItemIdRequest() {
        return new GetAllCategoriesByItemIdRequest();
    }

    /**
     * Create an instance of {@link GetAllCategoriesByItemIdResponse }
     * 
     */
    public GetAllCategoriesByItemIdResponse createGetAllCategoriesByItemIdResponse() {
        return new GetAllCategoriesByItemIdResponse();
    }

    /**
     * Create an instance of {@link GetItemCreationDataRequest }
     * 
     */
    public GetItemCreationDataRequest createGetItemCreationDataRequest() {
        return new GetItemCreationDataRequest();
    }

    /**
     * Create an instance of {@link GetCreationDataResponse }
     * 
     */
    public GetCreationDataResponse createGetCreationDataResponse() {
        return new GetCreationDataResponse();
    }

    /**
     * Create an instance of {@link CreateDataDto }
     * 
     */
    public CreateDataDto createCreateDataDto() {
        return new CreateDataDto();
    }

    /**
     * Create an instance of {@link GetBrandCreationDataRequest }
     * 
     */
    public GetBrandCreationDataRequest createGetBrandCreationDataRequest() {
        return new GetBrandCreationDataRequest();
    }

    /**
     * Create an instance of {@link GetCategoryCreationDataRequest }
     * 
     */
    public GetCategoryCreationDataRequest createGetCategoryCreationDataRequest() {
        return new GetCategoryCreationDataRequest();
    }

    /**
     * Create an instance of {@link GetManufacturerCreationDataRequest }
     * 
     */
    public GetManufacturerCreationDataRequest createGetManufacturerCreationDataRequest() {
        return new GetManufacturerCreationDataRequest();
    }

    /**
     * Create an instance of {@link AddressDto }
     * 
     */
    public AddressDto createAddressDto() {
        return new AddressDto();
    }

    /**
     * Create an instance of {@link MetaContainerDto }
     * 
     */
    public MetaContainerDto createMetaContainerDto() {
        return new MetaContainerDto();
    }

}
