//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.13 at 06:05:43 PM YEKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.producingservice.app.dto.database", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package database.dto.app.producingservice.com;
