//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.26 at 02:00:07 AM YEKT 
//


package com.producingservice.app.dto.items;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.producingservice.app.dto.items package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.producingservice.app.dto.items
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetItemByIdRequest }
     */
    public GetItemByIdRequest createGetItemByIdRequest() {
        return new GetItemByIdRequest();
    }

    /**
     * Create an instance of {@link GetItemByIdResponse }
     */
    public GetItemByIdResponse createGetItemByIdResponse() {
        return new GetItemByIdResponse();
    }

    /**
     * Create an instance of {@link ItemDto }
     */
    public ItemDto createItemDto() {
        return new ItemDto();
    }

    /**
     * Create an instance of {@link CreateItemRequest }
     */
    public CreateItemRequest createCreateItemRequest() {
        return new CreateItemRequest();
    }

    /**
     * Create an instance of {@link CreateItemResponse }
     */
    public CreateItemResponse createCreateItemResponse() {
        return new CreateItemResponse();
    }

    /**
     * Create an instance of {@link UpdateItemRequest }
     */
    public UpdateItemRequest createUpdateItemRequest() {
        return new UpdateItemRequest();
    }

    /**
     * Create an instance of {@link UpdateItemResponse }
     */
    public UpdateItemResponse createUpdateItemResponse() {
        return new UpdateItemResponse();
    }

    /**
     * Create an instance of {@link DeleteItemByIdRequest }
     */
    public DeleteItemByIdRequest createDeleteItemByIdRequest() {
        return new DeleteItemByIdRequest();
    }

    /**
     * Create an instance of {@link DeleteItemByIdResponse }
     */
    public DeleteItemByIdResponse createDeleteItemByIdResponse() {
        return new DeleteItemByIdResponse();
    }

    /**
     * Create an instance of {@link GetAllItemsRequest }
     */
    public GetAllItemsRequest createGetAllItemsRequest() {
        return new GetAllItemsRequest();
    }

    /**
     * Create an instance of {@link GetAllItemsResponse }
     */
    public GetAllItemsResponse createGetAllItemsResponse() {
        return new GetAllItemsResponse();
    }

}
